# version 字段不推荐
services:
  # Nginx 反向代理
  nginx:
    build: ./nginx
    # 添加端口映射, 将容器的 80 端口映射为宿主机的 8080
    ports:
      - "8080:80"
    # 依赖关系, 先启动后端和前端, 再启动nginx
    depends_on:
      - frontend
      - backend
    
  # 前端服务
  frontend:
    build: ./frontend
    # 暴露端口, 仅容器网络可见
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    # restart: on-failure
    
  # 后端服务
  backend:
    build: ./backend
    expose:
      - "3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todos
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    # restart: on-failure

  # MongoDB 数据库
  mongodb:
    image: mongo:6
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db

# 定义持久化存储卷
volumes:
  mongodb_data: 